// Generated by scripts/generate_cuda_typedefs.py from runtime/api/cuda.h.
// Do not edit by hand; rerun the generator after changing the driver API.
//
// Versioned driver entry-point typedefs in the shape of NVIDIA's
// cudaTypedefs.h. CuMetal exports each entry point once with the CUDA 12
// ABI, so every version of a name shares one signature.
#ifndef CUMETAL_CUDA_TYPEDEFS_H
#define CUMETAL_CUDA_TYPEDEFS_H

#include "cuda.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef CUresult (CUDAAPI *PFN_cuArray3DCreate_v3020)(CUarray* pHandle, const CUDA_ARRAY3D_DESCRIPTOR* pAllocateArray);
typedef CUresult (CUDAAPI *PFN_cuArrayCreate_v3020)(CUarray* pHandle, const CUDA_ARRAY_DESCRIPTOR* pAllocateArray);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuArrayDestroy_v2000)(CUarray hArray);
typedef CUresult (CUDAAPI *PFN_cuCtxCreate_v3020)(CUcontext* pctx, unsigned int flags, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuCtxDestroy_v4000)(CUcontext ctx);
typedef CUresult (CUDAAPI *PFN_cuCtxDisablePeerAccess_v4000)(CUcontext peerContext);
typedef CUresult (CUDAAPI *PFN_cuCtxEnablePeerAccess_v4000)(CUcontext peerContext, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuCtxGetCurrent_v4000)(CUcontext* pctx);
typedef CUresult (CUDAAPI *PFN_cuCtxGetDevice_v2000)(CUdevice* device);
typedef CUresult (CUDAAPI *PFN_cuCtxGetFlags_v7000)(unsigned int* flags);
typedef CUresult (CUDAAPI *PFN_cuCtxPopCurrent_v4000)(CUcontext* pctx);
typedef CUresult (CUDAAPI *PFN_cuCtxPushCurrent_v4000)(CUcontext ctx);
typedef CUresult (CUDAAPI *PFN_cuCtxSetCurrent_v4000)(CUcontext ctx);
typedef CUresult (CUDAAPI *PFN_cuCtxSynchronize_v2000)(void);
typedef CUresult (CUDAAPI *PFN_cuDeviceCanAccessPeer_v4000)(int* canAccessPeer, CUdevice dev, CUdevice peerDev);
typedef CUresult (CUDAAPI *PFN_cuDeviceComputeCapability_v2000)(int* major, int* minor, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDeviceGet_v2000)(CUdevice* device, int ordinal);
typedef CUresult (CUDAAPI *PFN_cuDeviceGetAttribute_v2000)(int* pi, CUdevice_attribute attrib, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDeviceGetCount_v2000)(int* count);
typedef CUresult (CUDAAPI *PFN_cuDeviceGetName_v2000)(char* name, int len, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDeviceGetUuid_v11040)(CUuuid* uuid, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDevicePrimaryCtxRelease_v11000)(CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDevicePrimaryCtxRetain_v7000)(CUcontext* pctx, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDeviceTotalMem_v3020)(size_t* bytes, CUdevice dev);
typedef CUresult (CUDAAPI *PFN_cuDriverGetVersion_v2020)(int* driverVersion);
typedef CUresult (CUDAAPI *PFN_cuEventCreate_v2000)(CUevent* phEvent, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuEventDestroy_v4000)(CUevent hEvent);
typedef CUresult (CUDAAPI *PFN_cuEventElapsedTime_v2000)(float* pMilliseconds, CUevent hStart, CUevent hEnd);
typedef CUresult (CUDAAPI *PFN_cuEventQuery_v2000)(CUevent hEvent);
typedef CUresult (CUDAAPI *PFN_cuEventRecord_v2000)(CUevent hEvent, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuEventRecordWithFlags_v11010)(CUevent hEvent, CUstream hStream, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuEventSynchronize_v2000)(CUevent hEvent);
typedef CUresult (CUDAAPI *PFN_cuFuncSetAttribute_v9000)(CUfunction hfunc, CUfunc_attribute attrib, int value);
typedef CUresult (CUDAAPI *PFN_cuGetErrorName_v6000)(CUresult error, const char** pStr);
typedef CUresult (CUDAAPI *PFN_cuGetErrorString_v6000)(CUresult error, const char** pStr);
typedef CUresult (CUDAAPI *PFN_cuGetProcAddress_v12000)(const char* symbol, void** pfn, int cudaVersion, uint64_t flags, CUdriverProcAddressQueryResult* symbolStatus);
typedef CUresult (CUDAAPI *PFN_cuGraphAddNode_v12030)(CUgraphNode* phGraphNode, CUgraph hGraph, const CUgraphNode* dependencies, const CUgraphEdgeData* dependencyData, size_t numDependencies, CUgraphNodeParams* nodeParams);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuGraphNodeGetDependentNodes_v10000)(CUgraphNode hNode, CUgraphNode* dependentNodes, size_t* numDependentNodes);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuGraphNodeGetType_v10000)(CUgraphNode hNode, CUgraphNodeType* type);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuGraphicsMapResources_v3000)(unsigned int count, CUgraphicsResource* resources, CUstream hStream);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuGraphicsResourceGetMappedPointer_v3020)(CUdeviceptr* pDevPtr, size_t* pSize, CUgraphicsResource resource);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuGraphicsUnmapResources_v3000)(unsigned int count, CUgraphicsResource* resources, CUstream hStream);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuGraphicsUnregisterResource_v3000)(CUgraphicsResource resource);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuInit_v2000)(unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuIpcCloseMemHandle_v4010)(CUdeviceptr dptr);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuIpcGetEventHandle_v4010)(CUipcEventHandle* pHandle, CUevent event);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuIpcGetMemHandle_v4010)(CUipcMemHandle* pHandle, CUdeviceptr dptr);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuIpcOpenEventHandle_v4010)(CUevent* phEvent, CUipcEventHandle handle);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuIpcOpenMemHandle_v11000)(CUdeviceptr* pdptr, CUipcMemHandle handle, unsigned int Flags);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuLaunchHostFunc_v10000)(CUstream hStream, CUhostFn fn, void* userData);
typedef CUresult (CUDAAPI *PFN_cuLaunchKernel_v4000)(CUfunction f, unsigned int gridDimX, unsigned int gridDimY, unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY, unsigned int blockDimZ, unsigned int sharedMemBytes, CUstream hStream, void** kernelParams, void** extra);
typedef CUresult (CUDAAPI *PFN_cuMemAlloc_v3020)(CUdeviceptr* dptr, size_t bytesize);
typedef CUresult (CUDAAPI *PFN_cuMemAllocHost_v3020)(void** pp, size_t bytesize);
typedef CUresult (CUDAAPI *PFN_cuMemAllocManaged_v6000)(CUdeviceptr* dptr, size_t bytesize, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuMemFree_v3020)(CUdeviceptr dptr);
typedef CUresult (CUDAAPI *PFN_cuMemFreeHost_v2000)(void* p);
typedef CUresult (CUDAAPI *PFN_cuMemGetInfo_v3020)(size_t* freeBytes, size_t* totalBytes);
typedef CUresult (CUDAAPI *PFN_cuMemHostAlloc_v2020)(void** pp, size_t bytesize, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuMemHostGetDevicePointer_v3020)(CUdeviceptr* pdptr, void* p, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuMemcpy2D_v3020)(const CUDA_MEMCPY2D* pCopy);
typedef CUresult (CUDAAPI *PFN_cuMemcpy2DAsync_v3020)(const CUDA_MEMCPY2D* pCopy, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemcpy3D_v3020)(const CUDA_MEMCPY3D* pCopy);
typedef CUresult (CUDAAPI *PFN_cuMemcpy3DAsync_v3020)(const CUDA_MEMCPY3D* pCopy, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemcpyBatchAsync_v12080)(CUdeviceptr* dsts, CUdeviceptr* srcs, size_t* sizes, size_t count, CUmemcpyAttributes* attrs, size_t* attrsIdxs, size_t numAttrs, size_t* failIdx, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemcpyDtoD_v3020)(CUdeviceptr dstDevice, CUdeviceptr srcDevice, size_t ByteCount);
typedef CUresult (CUDAAPI *PFN_cuMemcpyDtoDAsync_v3020)(CUdeviceptr dstDevice, CUdeviceptr srcDevice, size_t ByteCount, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemcpyDtoH_v3020)(void* dstHost, CUdeviceptr srcDevice, size_t ByteCount);
typedef CUresult (CUDAAPI *PFN_cuMemcpyDtoHAsync_v3020)(void* dstHost, CUdeviceptr srcDevice, size_t ByteCount, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemcpyHtoD_v3020)(CUdeviceptr dstDevice, const void* srcHost, size_t ByteCount);
typedef CUresult (CUDAAPI *PFN_cuMemcpyHtoDAsync_v3020)(CUdeviceptr dstDevice, const void* srcHost, size_t ByteCount, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemcpyPeerAsync_v4000)(CUdeviceptr dstDevice, CUcontext dstContext, CUdeviceptr srcDevice, CUcontext srcContext, size_t ByteCount, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemsetD32_v3020)(CUdeviceptr dstDevice, unsigned int ui, size_t N);
typedef CUresult (CUDAAPI *PFN_cuMemsetD32Async_v3020)(CUdeviceptr dstDevice, unsigned int ui, size_t N, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuMemsetD8_v3020)(CUdeviceptr dstDevice, unsigned char uc, size_t N);
typedef CUresult (CUDAAPI *PFN_cuMemsetD8Async_v3020)(CUdeviceptr dstDevice, unsigned char uc, size_t N, CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuModuleGetFunction_v2000)(CUfunction* hfunc, CUmodule hmod, const char* name);
typedef CUresult (CUDAAPI *PFN_cuModuleGetGlobal_v3020)(CUdeviceptr* dptr, size_t* bytes, CUmodule hmod, const char* name);
typedef CUresult (CUDAAPI *PFN_cuModuleLoad_v2000)(CUmodule* module, const char* fname);
typedef CUresult (CUDAAPI *PFN_cuModuleLoadData_v2000)(CUmodule* module, const void* image);
typedef CUresult (CUDAAPI *PFN_cuModuleLoadDataEx_v2010)(CUmodule* module, const void* image, unsigned int numOptions, void* options, void* optionValues);
typedef CUresult (CUDAAPI *PFN_cuModuleUnload_v2000)(CUmodule module);
typedef CUresult (CUDAAPI *PFN_cuPointerGetAttribute_v4000)(void* data, CUpointer_attribute attribute, CUdeviceptr ptr);
typedef CUresult (CUDAAPI *PFN_cuStreamAddCallback_v5000)(CUstream hStream, CUstreamCallback callback, void* userData, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuStreamCreate_v2000)(CUstream* phStream, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuStreamCreateWithPriority_v5050)(CUstream* phStream, unsigned int flags, int priority);
typedef CUresult (CUDAAPI *PFN_cuStreamDestroy_v4000)(CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuStreamGetCaptureInfo_v11030)(CUstream hStream, CUstreamCaptureStatus* captureStatus_out, cuuint64_t* id_out, CUgraph* graph_out, const CUgraphNode** dependencies_out, size_t* numDependencies_out);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuStreamGetCtx_v9020)(CUstream hStream, CUcontext* pctx);
typedef CUresult (CUDAAPI *PFN_cuStreamGetFlags_v5000)(CUstream hStream, unsigned int* flags);
typedef CUresult (CUDAAPI *PFN_cuStreamGetPriority_v5050)(CUstream hStream, int* priority);
typedef CUresult (CUDAAPI *PFN_cuStreamQuery_v2000)(CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuStreamSynchronize_v2000)(CUstream hStream);
typedef CUresult (CUDAAPI *PFN_cuStreamUpdateCaptureDependencies_v11030)(CUstream hStream, CUgraphNode* dependencies, size_t numDependencies, unsigned int flags);  // not implemented; cuGetProcAddress reports NOT_FOUND
typedef CUresult (CUDAAPI *PFN_cuStreamWaitEvent_v3020)(CUstream hStream, CUevent hEvent, unsigned int flags);
typedef CUresult (CUDAAPI *PFN_cuTexObjectCreate_v5000)(CUtexObject* pTexObject, const CUDA_RESOURCE_DESC* pResDesc, const CUDA_TEXTURE_DESC* pTexDesc, const CUDA_RESOURCE_VIEW_DESC* pResViewDesc);
typedef CUresult (CUDAAPI *PFN_cuTexObjectDestroy_v5000)(CUtexObject texObject);

#ifdef __cplusplus
}
#endif

#endif  // CUMETAL_CUDA_TYPEDEFS_H
